### ISSUE TITLE
Wann werden Initiativanträge behandelt?

### ISSUE THREAD

**Issue by scattenlaeufer** [ZaPF/Geschaeftsordnung_ZaPF#45]
Ich hatte auf der letzten ZaPF mit einigen Menschen die Diskussion, wann genau Initiativanträge behandelt werden. Mein persönliches Gefühl wäre, dass sie entweder unter den Punkt Sonstiges oder ans Ende der Liste der zu behandelnden Anträge fallen würden. Initiativanträge mit direktem inhaltlichem Bezug zu einem anderen Antrag sollten jedoch an passender Stelle bei diesem Antrag behandelt werden. Ein Beispiel für letzteres wären konkurrierende Initiativanträge zu bereits auf der TO verorteten Anträgen.

**Comment by behrmann** [comment]
Ja, das spiegelt ziemlich keine meine Interpretation der Lage wider. Ich bin immer davon ausgegangen, dass Initiativanträge hinten gequeued werden, aber Initiativanträge als konkurrierende Anträge durch die Auslegung der Sitzungsleitung welcher Antrag weitergehend ist implizit vorgezogen werden und danach im Zweifel erledigt sind.

**Comment by scattenlaeufer** [comment]
Und sollte eine groß genuge Menge an FSen der Meinung sein, dass ein für sich alleine stehender Initiativantrag früher behandelt werden sollte, kann man mit einem GO-Anträg zur Änderung der TO das ja immer herbeiführen.
