### ISSUE TITLE
Sollen Menschen auf der ZaPF/im Plenum anwesend sein um gewählt werden zu können?

### ISSUE THREAD

**Issue by scattenlaeufer** [ZaPF/Geschaeftsordnung_ZaPF#46]
Nach aktueller Formulierung von 4.2.1 muss man ausschließlich teilnehmende Person sein oder zur Wiederwahl stehen um das passive Wahlrecht zu genießen. Das bedeutet, dass eine nur den Teilnahmebeitrag entrichten, auf der ZaPF aber nicht anwesend sein muss um zum ersten Mal in ein Amt gewählt zu werden.

Dies widerspricht jedoch der eigentlichen Intention, nach der dem Plenum die Möglichkeit gegeben werden soll, eine Person kennen zu lernen bevor sie in ein Amt gewählt wird.

Es wäre also folgende Frage zu klären:

> Geht es bei dem Passus in 4.2.1 um die Anwesenheit im Plenum, bzw. der ZaPF, oder um das Entrichten des Teilnahembeitrags.

In ersterem Fall sollten wir die GO entsprechend anpassen und den Passus genauer Formulieren, in letzterem wäre nichts zu tun.

**Comment by behrmann** [comment]
Ich glaube schon, dass das so working as inteded ist. Ich meine mich zu erinnern, dass wir diesen Punkt damals so bei der Neufassung diskutiert haben und der Meinung waren, dass das Plenum wählen soll, wen es wählen will, da ein vollkommen unbekannter Mensch wohl nicht gewählt würde und das Bezahlen des Teilnahmebeitrages (bis dahin) immer vor Ort stattfand, d.h. die Person schon irgendwie da gewesen sein muss.

Wenn natürlich die Entrichtung jetzt per Vorkasse geht, dann ändert sich die Situation etwas. Ich glaube immernoch, dass eine vollkommen unbekannte Person nicht gewählt würde, aber eine bekannte Person könnte sich so in absentia wählen lassen, wenn sie das Geld überweist und aus irgendeinem Grund nicht kommt. Ich bin mir nicht sicher ob und wie sehr wir das einschränken wollen, da wir glaube ich auch schon nicht-konsekutive Wiederwahl in absentia zugelassen haben.

**Comment by scattenlaeufer** [comment]
Wenn ich mich recht entsinne ging es dabei nicht darum, ob eine Person
anwesend sein muss um gewählt zu werden, sondern welchen Status sie
dafür haben muss. Das geht jedenfalls aus dem
[Protokoll](https://zapf.wiki/SoSe16_AK_GO_und_Satzungsaenderung) des
entsprechenden AKs aus Konstanz hervor.

Deine Einschätzung, dass das Plenum eine ihm unbekannte Person nicht
wählen wrüde, teile ich nicht zu 100%. Besonders beim
Akkreditierungspool kann ich mich nur an eine Person erinnern, die nicht
gewählt wurde und gerade hier gibt es keine Möglichkeit zu
kontrollieren, ob Personen, die von uns entsandt wurden auch ordentliche
Arbeit tun.

Für alle anderen Posten stimme ich dir aber zu, dass eine Person, die
auf einer ZaPF nicht anwesend ist auch keine realistische Chance hat,
gewählt zu werden.
